repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the ref you want to point at
    hooks:
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: end-of-file-fixer

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
    - id: codespell
      additional_dependencies:
        - tomli

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
        args: [ --fix, --show-fixes ]
      - id: ruff-format

  - repo: https://github.com/scientific-python/cookie
    rev: "2024.01.24"
    hooks:
      - id: sp-repo-review
