sonar.projectKey=cta-observatory_ctapipe_io_zfits_67c2e9a0-0b65-4562-8229-84d956e3c95e
sonar.language=python
sonar.python.coverage.reportPaths=coverage/coverage.xml
sonar.python.version=3.12

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*test_*.py,**/tests/**/*.py
sonar.exclusions=**/*test_*.py,**/tests/**/*.py
