name: Deploy to PyPi

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    # "trusted publisher" config, see
    # https://docs.pypi.org/trusted-publishers/using-a-publisher/
    environment:
      name: pypi
      url: https://pypi.org/p/ctapipe-io-zfits
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      # make sure we have version info
      - run: git fetch --tags

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python --version
          pip install -U build
          python -m build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
